@startuml
WAIT_ENQUEUE --> WAIT_DEQUEUE : EVENT_ENQUEUE
INIT --> WAIT_CREATE : EVENT_RECV_DATA
WAIT_DEQUEUE --> WAIT_RESULT : EVENT_DEQUEUE
WAIT_RESULT --> OPEN_FAIL : EVENT_RESULT_FAIL
WAIT_RESULT --> OPEN_SUCCESS : EVENT_RESULT_SUCCESS
WAIT_CREATE --> WAIT_ENQUEUE : EVENT_CREATE
@enduml